import bs58check from 'bs58check';
import { tz5 } from '../../../test-fixtures/tz5';
import { prefixV2 } from '../src/constants';
import {
  b58DecodeAddress,
  b58DecodeAndCheckPrefix,
  b58DecodePublicKey,
  b58DecodePublicKeyHash,
  encodeAddress,
  encodeKey,
  encodeKeyHash,
  getPkhfromPk,
  payloadLength,
  validateAddress,
  validateKeyHash,
  validatePublicKey,
  validateSignature,
  ValidationResult,
  verifySignature,
} from '../src/taquito-utils';

describe('tz5 / ML-DSA-44 Octez reference vectors', () => {
  it.each([
    ['tz5', [6, 161, 169], 20],
    ['mdpk', [13, 7, 237, 67], 1312],
    ['mdsk', [9, 57, 116, 57], 3872],
    ['mdesk', [5, 49, 133, 39, 172], 3896],
    ['mdsig', [1, 156, 45, 210, 3], 2420],
  ])('registers the Octez %s encoding', (prefix, bytes, length) => {
    expect(prefixV2).toHaveProperty(prefix, Uint8Array.from(bytes));
    expect(payloadLength).toHaveProperty(prefix, length);
  });

  it('recognizes a tz5 address and public key hash', () => {
    expect(validateAddress(tz5.publicKeyHash)).toBe(ValidationResult.VALID);
    expect(validateKeyHash(tz5.publicKeyHash)).toBe(ValidationResult.VALID);
  });

  it('recognizes Octez public keys and signatures', () => {
    expect(validatePublicKey(tz5.publicKey)).toBe(ValidationResult.VALID);
    expect(validateSignature(tz5.signatures.plain)).toBe(ValidationResult.VALID);
  });

  it.each([
    ['tz5', tz5.publicKeyHash, 20],
    ['mdpk', tz5.publicKey, 1312],
    ['mdsk', tz5.secretKey, 3872],
    ['mdesk', tz5.encryptedSecretKey, 3896],
    ['mdsig', tz5.signatures.plain, 2420],
  ])('decodes the complete %s payload', (prefix, encoded, length) => {
    const [payload, actualPrefix] = b58DecodeAndCheckPrefix(encoded);
    expect(actualPrefix).toBe(prefix);
    expect(payload).toHaveLength(length);
  });

  it('matches Octez optimized address and key encodings in both directions', () => {
    const address = tz5.packed.address.slice(12);
    const keyHash = tz5.packed.keyHash.slice(12);
    const publicKey = tz5.packed.publicKey.slice(12);
    expect(b58DecodeAddress(tz5.publicKeyHash)).toBe(address);
    expect(encodeAddress(address)).toBe(tz5.publicKeyHash);
    expect(b58DecodePublicKeyHash(tz5.publicKeyHash)).toBe(keyHash);
    expect(encodeKeyHash(keyHash)).toBe(tz5.publicKeyHash);
    expect(b58DecodePublicKey(tz5.publicKey)).toBe(publicKey);
    expect(encodeKey(publicKey)).toBe(tz5.publicKey);
  });

  it('derives the address independently generated by Octez', () => {
    expect(getPkhfromPk(tz5.publicKey)).toBe(tz5.publicKeyHash);
  });

  it('verifies an Octez signature without a watermark', () => {
    expect(verifySignature(tz5.message, tz5.publicKey, tz5.signatures.plain)).toBe(true);
  });

  it('verifies an Octez operation watermark separately or as part of the message', () => {
    expect(
      verifySignature(tz5.message, tz5.publicKey, tz5.signatures.operation, new Uint8Array([3]))
    ).toBe(true);
    expect(verifySignature(`03${tz5.message}`, tz5.publicKey, tz5.signatures.operation)).toBe(true);
  });

  it('rejects a different message, key, or watermark', () => {
    expect(verifySignature('00', tz5.publicKey, tz5.signatures.plain)).toBe(false);
    expect(verifySignature(tz5.message, tz5.otherPublicKey, tz5.signatures.plain)).toBe(false);
    expect(verifySignature(tz5.message, tz5.publicKey, tz5.signatures.operation)).toBe(false);
    expect(
      verifySignature(tz5.message, tz5.publicKey, tz5.signatures.operation, new Uint8Array([5]))
    ).toBe(false);
  });

  it('rejects a changed signature with a valid Base58 checksum', () => {
    const bytes = bs58check.decode(tz5.signatures.plain);
    bytes[5] ^= 1;
    expect(verifySignature(tz5.message, tz5.publicKey, bs58check.encode(bytes))).toBe(false);
  });

  it.each([
    ['address', tz5.publicKeyHash],
    ['public key', tz5.publicKey],
    ['secret key', tz5.secretKey],
    ['encrypted secret key', tz5.encryptedSecretKey],
    ['signature', tz5.signatures.plain],
  ])('rejects truncated and oversized %s payloads with valid checksums', (_, encoded) => {
    const bytes = bs58check.decode(encoded);
    expect(() => b58DecodeAndCheckPrefix(bs58check.encode(bytes.subarray(0, -1)))).toThrow();
    expect(() =>
      b58DecodeAndCheckPrefix(bs58check.encode(Buffer.concat([bytes, Buffer.from([0])])))
    ).toThrow();
  });

  it('rejects a bad address checksum', () => {
    const corrupted =
      tz5.publicKeyHash.slice(0, -1) + (tz5.publicKeyHash.endsWith('1') ? '2' : '1');
    expect(validateAddress(corrupted)).toBe(ValidationResult.INVALID_CHECKSUM);
  });
});
