//export const base_url = "https://tezostaquito.io/docs/next/"
export const base_url = "https://7d7eaa4d--tezostaquito.netlify.app/docs/next/"
export const disclaimer = "This is unreleased documentation for Taquito Next version."
export const runButton = "[class='button_G4Yn runButton_oaHB']"
export const playgroundPreview = "[class='playgroundPreview_bb8I']"