taq originate SaplingLiveCodeContract.tz -e testing
taq originate IncrementContract.tz -e testing
taq originate MichelsonMapContract.tz -e testing
taq originate LambdaViewContract.tz -e testing
taq originate LambdaViewWithTokenContract.tz -e testing
taq originate MapWithWithSingleMapForStorage.tz -e testing 
taq originate MapWithPairasMapContract.tz -e testing
taq originate MapWithComplexKeysContract.tz -e testing
taq originate MapWithInitialStorageContract.tz -e testing
taq originate BigMapsMultipleValuesContract.tz -e testing
taq originate BigMapsComplexStorageContract.tz -e testing 
taq originate ContractCallFib.tz -e testing 
taq originate ContractTopLevelViews.tz -e testing
taq originate TokenContract.tz -e testing 
taq originate Tzip16StorageContract.tz -e testing 
taq originate Tzip16HTTPSContract.tz -e testing
taq originate Tzip16SHA256Contract.tz -e testing
taq originate Tzip16IPFSContract.tz -e testing 
taq originate Tzip16OffChainContractJSON.tz -e testing 
taq originate Tzip16OffChainContractMultiply.tz -e testing 
taq originate WalletContract.tz -e testing 
taq originate WalletAreYouThereContract.tz -e testing 
taq originate BigMapPackContract.tz -e testing 