export const knownContractProtoALph = "KT1RGr4RZKGJTtRhWS7Awrf9mdDY3X8hWGXf";
export const knownBigMapContractProtoALph = "KT1RqJRpocvvtqygn1YUko9VGzJpXYvX2FQ5";
export const knownTzip12BigMapOffChainContractProtoALph = "KT1N8ztbzbh4rb4nNQ5ANv9DdbWbqDRy4w9W";
export const knownSaplingContractProtoALph = "KT1Uye8Y7SoJmPAR723J5BS9dekzSkTnkdKY";
export const knownOnChainViewContractAddressProtoALph = "KT1UF7P8fRGiapqyAkpFYpMLuBujbGdHyRum";