#!/bin/sh
export RUN_PARISNET_WITH_SECRET_KEY=true
export SECRET_KEY=edsk3QoqBuvdamxouPhin7swCvkQNgq4jP5KZPbwWNnwdZpSpJiEbq
export TEZOS_RPC_PARISNET=http://localhost:8732
export POLLING_INTERVAL_MILLISECONDS=100
export RPC_CACHE_MILLISECONDS=0
export TEZOS_BAKER=tz1faswCTDciRzE4oJ9jn2Vm2dvjeyA9fUzU