#!/bin/sh
export RUN_LIMANET_WITH_SECRET_KEY=true
export SECRET_KEY=edsk3RFgDiCt7tWB2oe96w1eRw72iYiiqZPLu9nnEY23MYRp2d8Kkx
export TEZOS_RPC_LIMANET=http://localhost:20001
export RPC_CACHE_MILLISECONDS=0
export TEZOS_BAKER=tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb
