import { OpKind } from '@taquito/rpc';

export const BATCH_KINDS = [
  OpKind.ACTIVATION,
  OpKind.ORIGINATION,
  OpKind.TRANSACTION,
  OpKind.DELEGATION,
  OpKind.REGISTER_GLOBAL_CONSTANT,
  OpKind.INCREASE_PAID_STORAGE,
  OpKind.TRANSFER_TICKET,
  OpKind.SMART_ROLLUP_ADD_MESSAGES,
  OpKind.SMART_ROLLUP_ORIGINATE,
  OpKind.SMART_ROLLUP_EXECUTE_OUTBOX_MESSAGE,
];

export type BatchKinds =
  | OpKind.ACTIVATION
  | OpKind.ORIGINATION
  | OpKind.TRANSACTION
  | OpKind.DELEGATION
  | OpKind.REGISTER_GLOBAL_CONSTANT
  | OpKind.INCREASE_PAID_STORAGE
  | OpKind.TRANSFER_TICKET
  | OpKind.SMART_ROLLUP_ADD_MESSAGES
  | OpKind.SMART_ROLLUP_ORIGINATE
  | OpKind.SMART_ROLLUP_EXECUTE_OUTBOX_MESSAGE;
